import { globSync } from "node:fs";
import { path } from "@staticbolt/core";

import { applyOrdering, normalizeTitle, parseSidebarFrontmatter } from "./helpers.ts";
import { renderTree } from "./render-tree.ts";

import type { RequiredOptions, SidebarDirectory, SidebarTree } from "./types.ts";
import type { App } from "@staticbolt/core";

function getOrCreateDirectory(tree: SidebarTree, title: string, realPath: string): SidebarDirectory {
  let directory = tree.find((entry): entry is SidebarDirectory => "items" in entry && entry.title === title);

  if (!directory) {
    directory = { title, realPath, collapsed: false, items: [] };
    tree.push(directory);
  }

  return directory;
}

export function generateTree(this: App, options: RequiredOptions) {
  const { include, exclude, baseDirectory } = options;

  const autoGenerated: SidebarTree = [];

  // Sort files to guarantee a consistent, alphabetical filesystem order regardless
  // of the platform-specific order that globSync may return them in.
  const files = globSync(include, { cwd: this.root, exclude }).toSorted();

  for (let file of files) {
    file = path.normalize(file);

    const parts = file.split("/");
    if (!parts.includes(baseDirectory)) continue;

    const directories = parts.filter((_, index) => index > parts.indexOf(baseDirectory));

    const fileName = directories.pop();
    if (!fileName) continue;

    if (path.extname(fileName) === ".md") {
      const sidebarFrontmatter = parseSidebarFrontmatter(file);

      if (sidebarFrontmatter.node) {
        options.customizations[file] ??= {};
        Object.assign(options.customizations[file], sidebarFrontmatter.node);
      }

      if (sidebarFrontmatter.parent) {
        const parentPath = path.dirname(file);
        options.customizations[parentPath] ??= {};
        Object.assign(options.customizations[parentPath], sidebarFrontmatter.parent);
      }
    }

    let currentTree = autoGenerated;
    const baseIndex = parts.indexOf(baseDirectory);
    let realDirectoryPath = parts.slice(0, baseIndex + 1).join("/");

    for (const directory of directories) {
      realDirectoryPath = path.join(realDirectoryPath, directory);
      const title = normalizeTitle(directory);
      currentTree = getOrCreateDirectory(currentTree, title, realDirectoryPath).items;
    }

    const fileNameWithoutExtension = path.parse(fileName).name;

    const title = normalizeTitle(fileNameWithoutExtension);

    const pathAsLink =
      fileNameWithoutExtension === "index" ? path.dirname(file) : path.join(path.dirname(file), fileNameWithoutExtension);

    // Sidebar link is relative to the "sidebar" layout where it will be injected
    const href = path.relative(path.dirname(options.sidebarLayout.path), pathAsLink) + "/";

    currentTree.push({ title, filePath: href, realPath: file });
  }

  // Apply explicit order customizations on top of the filesystem order.
  applyOrdering(autoGenerated, options.customizations);

  return `<ul class="sidebar-list" slot="${options.sidebarLayout.slotName}">${renderTree(autoGenerated, options)}</ul>`;
}
